# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories

# Paths to exclude from secret scanning
# These paths contain documentation and examples with template/placeholder credentials
paths-ignore:
  - 'docs/**/*.md'  # Documentation with connection string examples
  - 'tests/fixtures/**'  # Test fixtures may contain mock credentials
  - '**/*_test.py'  # Test files with mock data
  - '**/test_*.py'  # Test files with mock data
  - '.env.template'  # Template file with placeholder examples
